### PR TITLE
Use LESS-specific syntax

### PR DESCRIPTION
**Pull request by s7eph4n**
Some straightforward optimizations.
Further optimization should be possible, but would need more analysis of what stuff is doing.

### CODE REVIEW

**Comment by kghbln** [comment]
@s7eph4n Cool! Thanks a lot for converting the CSS syntax into the LESS syntax. This was on my list for a later point in time. I just moved it in at s-mw.o and you can see for yourself.

I am personally already using Chameleon for a couple of weeks now. There are about three blockers and hope to get rid of them soon.

**Comment by kghbln** [comment]
@s7eph4n Is there some css-less-converter you could recommend or is this pure love what I am seeing here?

**Comment by s7eph4n** [comment]
There are some to be found via Google, but I don't know any that I can recommend in particular. 
This patch was done by hand to preserve comments.

**Comment by kghbln** [comment]
Wow, thanks a lot!

**Comment by mwjames** [comment]
I don't want to crush the party but I think during the conversion we lost something with non links appearing as

image

and li elements are shown as 

image

**Comment by kghbln** [comment]
> I don't want to crush the party but I think during the conversion we lost something with non links appearing as

I have seen this but did not have had the time to look at this. This was not happening when I used classic CSS so the less syntax needs to be tweaked.

Unfortunately there are two other blockers for switching to the new skin which make this issue appear as a non-issue. In on case I have to investigate a tipp from Stephan and in one case I have not the slightest idea on which keywords to even enter into the google search.

**Comment by s7eph4n** [comment]
I'll have a look.

-------- Original Message --------

**Comment by s7eph4n** [comment]
Ok, I think I fixed this in #6.

It might make sense to also integrate smw.org's MediaWiki:Chameleon.css in stragula.less. That way you don't need so many `!important` modifiers.

**Comment by kghbln** [comment]
> It might make sense to also integrate smw.org's MediaWiki:Chameleon.css in stragula.less. That way you don't need so many !important modifiers.

I am pretty mad now. I thought to have cleared all this stuff.

**Comment by kghbln** [comment]
> Ok, I think I fixed this in #6.

Affirmative, this is fixed now.

**Pull request merged**
